# Generated by Django 5.2.8 on 2025-11-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(help_text='Enter Employee Name', max_length=20)),
                ('age', models.IntegerField(help_text='Enter Employee Age')),
                ('dob', models.DateField()),
                ('Employee_id', models.IntegerField(help_text='Enter Employee ID')),
            ],
        ),
    ]
